import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import '../app_constants.dart';

class AttendanceScreen extends StatefulWidget {
  const AttendanceScreen({super.key});
  @override State<AttendanceScreen> createState() => _AttendanceScreenState();
}

class _AttendanceScreenState extends State<AttendanceScreen> {
  final MobileScannerController _ctrl = MobileScannerController();
  bool _showScanner = false, _processing = false;
  String? _lastResult;

  @override
  void dispose() { _ctrl.dispose(); super.dispose(); }

  Future<void> _onDetect(BarcodeCapture capture) async {
    if (_processing) return;
    final barcode = capture.barcodes.firstOrNull;
    if (barcode?.rawValue == null) return;
    final scanned  = barcode!.rawValue!;
    final today    = DateTime.now().toIso8601String().substring(0, 10);
    final expected = 'agency_ops_attendance_$today';

    if (scanned != expected) {
      setState(() { _lastResult = '❌ Invalid or expired QR code.'; _showScanner = false; });
      return;
    }
    setState(() => _processing = true);
    try {
      if (await isMonthLocked()) { setState(() { _lastResult = '🔒 Month is locked. No points awarded.'; _showScanner = false; }); return; }
      final uid = FirebaseAuth.instance.currentUser?.uid;
      if (uid == null) throw Exception('Not authenticated');
      await usersCol.doc(uid).set({
        'points': FieldValue.increment(attendancePoints),
        'last_attendance': FieldValue.serverTimestamp(),
        'last_updated': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));
      await logEvent(type: 'ATTENDANCE', description: 'QR attendance scanned (+$attendancePoints pts)');
      setState(() { _lastResult = '✅ Attendance logged! +$attendancePoints points awarded.'; _showScanner = false; });
    } catch (e) {
      setState(() { _lastResult = '⚠️ Error: $e'; _showScanner = false; });
    } finally { setState(() => _processing = false); }
  }

  @override
  Widget build(BuildContext context) {
    final today        = DateTime.now().toIso8601String().substring(0, 10);
    final secureQrData = 'agency_ops_attendance_$today';

    return SingleChildScrollView(padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 32), child: Column(children: [
      Text('Secure Attendance', style: GoogleFonts.inter(fontSize: 24, fontWeight: FontWeight.w800, color: Colors.white)),
      const SizedBox(height: 8),
      Text('Scan the daily QR generated by the administrator to log your entry.', textAlign: TextAlign.center, style: GoogleFonts.inter(color: Colors.white38, fontSize: 13, height: 1.5)),
      const SizedBox(height: 32),
      
      // ── Admin QR Section ──
      Container(
        padding: const EdgeInsets.all(24),
        decoration: BoxDecoration(
          color: kCard, borderRadius: BorderRadius.circular(28), border: Border.all(color: kBorder),
          boxShadow: [BoxShadow(color: Colors.black.withValues(alpha: 0.3), blurRadius: 40, offset: const Offset(0, 15))],
        ),
        child: Column(children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(20)),
            child: QrImageView(data: secureQrData, version: QrVersions.auto, size: 200.0, eyeStyle: const QrEyeStyle(eyeShape: QrEyeShape.square, color: Colors.black)),
          ),
          const SizedBox(height: 16),
          Text(today, style: GoogleFonts.inter(letterSpacing: 1.2, fontWeight: FontWeight.w700, color: kMuted, fontSize: 12)),
          const SizedBox(height: 8),
          const Text('ADMIN DISPLAY ONLY', style: TextStyle(color: Colors.white24, fontWeight: FontWeight.w800, fontSize: 10)),
        ]),
      ),
      
      const SizedBox(height: 40),

      if (_lastResult != null) ...[
        _resultCard(),
        const SizedBox(height: 16),
      ],

      if (!_showScanner) 
        SizedBox(width: double.infinity, child: FilledButton(
          style: FilledButton.styleFrom(
            backgroundColor: kAccent, padding: const EdgeInsets.symmetric(vertical: 18),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
            elevation: 8, shadowColor: kAccent.withValues(alpha: 0.4),
          ),
          onPressed: () => setState(() { _showScanner = true; _lastResult = null; }),
          child: Row(mainAxisAlignment: MainAxisAlignment.center, children: const [
            Icon(Icons.camera_alt_rounded, size: 20),
            SizedBox(width: 12),
            Text('Scan QR to Check-In', style: TextStyle(fontWeight: FontWeight.w700, fontSize: 16)),
          ]),
        ))
      else ...[
        Stack(alignment: Alignment.center, children: [
          ClipRRect(borderRadius: BorderRadius.circular(24),
            child: SizedBox(height: 300, child: MobileScanner(controller: _ctrl, onDetect: _onDetect))),
          // Scanner Frame Overlay
          _scannerOverlay(),
          if (_processing) const CircularProgressIndicator(color: Colors.white),
        ]),
        const SizedBox(height: 16),
        TextButton.icon(icon: const Icon(Icons.close), label: const Text('Cancel Scanning'), onPressed: () => setState(() => _showScanner = false), style: TextButton.styleFrom(foregroundColor: Colors.white38)),
      ],
      
      const SizedBox(height: 32),
      _infoPanel(),
    ]));
  }

  Widget _scannerOverlay() => Container(
    width: 200, height: 200,
    decoration: BoxDecoration(
      border: Border.all(color: kAccent, width: 2),
      borderRadius: BorderRadius.circular(20),
    ),
    child: Stack(children: [
       Align(alignment: Alignment.topCenter, child: Container(width: 180, height: 2, decoration: BoxDecoration(color: kAccent, boxShadow: [BoxShadow(color: kAccent, blurRadius: 10, spreadRadius: 2)]))),
    ]),
  );

  Widget _resultCard() => Container(
    width: double.infinity, padding: const EdgeInsets.all(20),
    decoration: BoxDecoration(
      color: (_lastResult!.startsWith('✅') ? Colors.greenAccent : Colors.redAccent).withValues(alpha: 0.1),
      borderRadius: BorderRadius.circular(16),
      border: Border.all(color: (_lastResult!.startsWith('✅') ? Colors.greenAccent : Colors.redAccent).withValues(alpha: 0.3)),
    ),
    child: Column(children: [
      Icon(_lastResult!.startsWith('✅') ? Icons.check_circle_rounded : Icons.warning_amber_rounded, color: _lastResult!.startsWith('✅') ? Colors.greenAccent : Colors.redAccent, size: 32),
      const SizedBox(height: 12),
      Text(_lastResult!, textAlign: TextAlign.center, style: GoogleFonts.inter(fontWeight: FontWeight.w700, color: Colors.white)),
    ]),
  );

  Widget _infoPanel() => Container(
    width: double.infinity, padding: const EdgeInsets.all(16),
    decoration: BoxDecoration(color: kCard, borderRadius: BorderRadius.circular(16), border: Border.all(color: kBorder)),
    child: Row(children: [
      const Icon(Icons.stars_rounded, color: Colors.amberAccent, size: 24),
      const SizedBox(width: 16),
      Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        const Text('Daily Reward Pool', style: TextStyle(color: Colors.white, fontWeight: FontWeight.w700, fontSize: 13)),
        Text('Scan daily to earn $attendancePoints pts towards your profit share.', style: const TextStyle(color: Colors.white38, fontSize: 11)),
      ])),
    ]),
  );
}
